name: 'reddit_ads_source'
version: '0.1.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  reddit_ads_source:
    account: "{{ source('reddit_ads', 'account') }}"
    account_report: "{{ source('reddit_ads', 'account_report') }}"
    ad: "{{ source('reddit_ads', 'ad') }}"
    ad_report: "{{ source('reddit_ads', 'ad_report') }}"
    ad_group: "{{ source('reddit_ads', 'ad_group') }}"
    ad_group_report: "{{ source('reddit_ads', 'ad_group_report') }}"
    campaign: "{{ source('reddit_ads', 'campaign') }}"
    campaign_report: "{{ source('reddit_ads', 'campaign_report') }}"
    post_report: "{{ source('reddit_ads', 'post_report') }}"
    campaign_conversions_report: "{{ source('reddit_ads', 'campaign_conversions_report') }}"
    post_conversions_report: "{{ source('reddit_ads', 'post_conversions_report') }}"

  # add vars
  #  add pass through metrics?
  reddit_ads__account_passthrough_metrics: []
  
models:
  reddit_ads_source:
    +schema: reddit_ads_source
    +materialized: table
    tmp:
      +materialized: view
