name: 'reddit_ads_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests'
config-version: 2

vars: 
  reddit_ads_schema: reddit_ads_source_integration_tests
  # -- add identifiers

seeds:
  reddit_ads_source_integration_tests:
    +column_types:

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
