name: 'reddit_ads_source_integration_tests'
version: '0.3.0'

profile: 'integration_tests'
config-version: 2

vars:
  reddit_ads_schema: zz_reddit #reddit_ads_source_integration_tests
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_account_conversions_report_identifier: "reddit_ads_account_conversions"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_conversions_report_identifier: "reddit_ads_ad_conversions"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_ad_group_conversions_report_identifier: "reddit_ads_ad_group_conversions"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"
  reddit_ads_campaign_conversions_report_identifier: "reddit_ads_campaign_conversions"
  reddit_ads_campaign_country_report_identifier: "reddit_ads_campaign_country_report_data"
  reddit_ads_campaign_country_conversions_report_identifier: "reddit_ads_campaign_country_conversions_report_data"

  reddit_ads__campaign_conversions_passthrough_metrics:
    - name: avg_value 
  reddit_ads__account_conversions_passthrough_metrics:
    - name: view_through_conversion_attribution_window_week
  reddit_ads__ad_conversions_passthrough_metrics:
    - name: click_through_conversion_attribution_window_week
  reddit_ads__ad_group_conversions_passthrough_metrics:
    - name: view_through_conversion_attribution_window_day

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  reddit_ads_source_integration_tests:
    +column_types:
      id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"