name: 'reddit_ads_source_integration_tests'
version: '0.6.1'

profile: 'integration_tests'
config-version: 2

vars:
  reddit_ads_schema: reddit_ads_source_integration_tests
  reddit_ads_account_identifier: "reddit_ads_account_data"
  reddit_ads_business_account_identifier: "reddit_ads_business_account_data"
  reddit_ads_account_report_identifier: "reddit_ads_account_report_data"
  reddit_ads_account_conversions_report_identifier: "reddit_ads_account_conversions"
  reddit_ads_ad_identifier: "reddit_ads_ad_data"
  reddit_ads_ad_report_identifier: "reddit_ads_ad_report_data"
  reddit_ads_ad_conversions_report_identifier: "reddit_ads_ad_conversions"
  reddit_ads_ad_group_identifier: "reddit_ads_ad_group_data"
  reddit_ads_ad_group_report_identifier: "reddit_ads_ad_group_report_data"
  reddit_ads_ad_group_conversions_report_identifier: "reddit_ads_ad_group_conversions"
  reddit_ads_campaign_identifier: "reddit_ads_campaign_data"
  reddit_ads_campaign_report_identifier: "reddit_ads_campaign_report_data"
  reddit_ads_campaign_conversions_report_identifier: "reddit_ads_campaign_conversions"
  reddit_ads_campaign_country_report_identifier: "reddit_ads_campaign_country_report_data"
  reddit_ads_campaign_country_conversions_report_identifier: "reddit_ads_campaign_country_conversions_report_data"

  ## Comment out when generating docs!
  reddit_ads__campaign_conversions_passthrough_metrics:
    - name: avg_value 
  reddit_ads__account_conversions_passthrough_metrics:
    - name: view_through_conversion_attribution_window_week
  reddit_ads__ad_conversions_passthrough_metrics:
    - name: click_through_conversion_attribution_window_week
  reddit_ads__ad_group_conversions_passthrough_metrics:
    - name: view_through_conversion_attribution_window_day

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +docs:
    show: false
  reddit_ads_source_integration_tests:
    reddit_ads_ad_data:
      +column_types:
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_report_data:
      +column_types:
        ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_data:
      +column_types:
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_report_data:
      +column_types:
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_data:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_report_data:
      +column_types:
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_country_report_data:
      +column_types:
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_country_conversions_report_data:
      +column_types:
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_account_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_business_account_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_account_conversions:
      +column_types:
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_conversions:
      +column_types:
        ad_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_ad_group_conversions:
      +column_types:
        ad_group_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    reddit_ads_campaign_conversions:
      +column_types:
        campaign_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
        account_id: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"